"""integrity constraint for topic table

Revision ID: ab6a61790506
Revises: fae0a7a30716
Create Date: 2025-09-08 15:46:49.319012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab6a61790506'
down_revision: Union[str, Sequence[str], None] = 'fae0a7a30716'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_topic_title', 'topics', ['title', 'user_id'])
    op.drop_column('topics', 'tags')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('tags', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_constraint('uq_user_topic_title', 'topics', type_='unique')
    # ### end Alembic commands ###
